### ISSUE TITLE
Add support for multiple types

### ISSUE THREAD

**Issue by andreafalzetti** [invopop/jsonschema#134] opened 2024-02-09 11:59 UTC
Currently `Type` is `string`. But JsonSchema allow for [MultiTypes](https://cswr.github.io/JsonSchema/spec/multiple_types/)

**Comment by samlown** [comment] 2024-02-19 22:40
A proposal that solves this would be great but I don't think the amount of pain involved in Go to get this working is worth it, especially given that this library is more concerned about converting Go to JSON Schema. Happy to hear more opinions, but I'll close this for the time being.

**Closed by samlown** 2024-02-19 22:40 UTC

**Comment by cpuguy83** [comment] 2025-02-12 00:12
The issue is since the the Schema type does not support multiple types we can't even modify the schema after its generated to deal with it (outside of maybe using a marshalling/unmarshalling to a different type).
